return {
  opt = {
    relativenumber = true,
    number = true,
    spell = false,
    signcolumn = "auto",
    wrap = false,
    colorcolumn = "120",
    updatetime = 50,
    showtabline = 0,
    guifont = "FiraMono Nerd Font:h15",
  },
  g = {
    mapleader = " ",
    autoformat_enabled = true,
    cmp_enabled = true,
    autopairs_enabled = true,
    diagnostics_mode = 3,
    icons_enabled = true,
    ui_notifications_enabled = true,
    resession_enabled = false,
    lsp_document_highlight_enabled = 1,
    move_key_modifier_visualmode = "S",
    transparency = 0.9,
    neovide_scroll_animation_length = 0.2,
    neovide_cursor_trail_size = 0.2,
    neovide_refresh_rate = 144,
    neovide_transparency = 0.9,
  },
}
